#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
zsh_path=$(zsh -c 'source ~/.zshrc && echo $PATH') # 将 zsh 的 PATH 保存到一个变量
export PATH="$zsh_path" 
echo "zsh path ${PATH}"
PATH="/usr/local/bin:$PATH"
npx lint-staged