name: Code Quality

on:
  workflow_call:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Check types
        run: pnpm run check-types

      - name: Lint
        run: pnpm run lint

      - name: Check package.json
        run: |
          # 检查package.json格式
          node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
          echo "✅ package.json is valid JSON"

      - name: Check for console.log statements
        run: |
          if grep -r "console\.log" src/; then
            echo "❌ Found console.log statements in source code"
            exit 1
          else
            echo "✅ No console.log statements found"
          fi

      - name: Check for TODO comments
        run: |
          if grep -r "TODO" src/; then
            echo "⚠️  Found TODO comments in source code"
          else
            echo "✅ No TODO comments found"
          fi

      - name: Check file sizes
        run: |
          echo "📊 Checking file sizes..."
          find src/ -name "*.ts" -exec wc -l {} + | sort -nr | head -10
