name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GOOGLE_RELEASE_TOKEN }}
          config-file: .release-please-config.json

      - name: Log release result
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Tag: ${{ steps.release.outputs.tag_name }}"
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Changelog: ${{ steps.release.outputs.changelog }}"
